name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-push-images:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      push_images: true
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
